### ISSUE TITLE
can we have the ue4 version too?

### ISSUE THREAD

**Issue by oralhighjene** [RobowilOFFICIAL/MugenEngine-UE5#16]
i dont have enough storage to use ue5, and i dont have a powerful pc to run ue5

**Comment by RobowilOFFICIAL** [comment]
Can be found [here](https://www.youtube.com/watch?v=FXQx6cjZQsc)

**Comment by oralhighjene** [comment]
thanks man!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
