### ISSUE TITLE
Not working on UE5.0.2

### ISSUE THREAD

**Issue by mhossein1384** [RobowilOFFICIAL/MugenEngine-UE5#3]
Does not work on Unreal engine 5.0.2
-Crashes at startup

**Comment by RobowilOFFICIAL** [comment]
Odd. It works on 5.0.2 on my end. Part of me feels that it could just be something related to file path length, as Unreal doesn't seem to like long filepath names at all. As such, I was unable to reproduce your issue.

**Comment by HerogonStudios** [comment]
This is what I'm getting for the crash:

LoginId:9c557af6844086e4411e889ba367ceca
EpicAccountId:f676fdb1b6e346f88211354651eebc05

Assertion failed: IsValid(Platform) [File:/Users/build/Build/++UE5/Sync/Engine/Source/Runtime/RHI/Public/RHIDefinitions.h] [Line: 461]

PlatformCreateDynamicRHI() Address = 0x10730f726 (filename not found) [in UnrealEditor-RHI.dylib]
RHIInit(bool) Address = 0x107310ff8 (filename not found) [in UnrealEditor-RHI.dylib]
FEngineLoop::PreInitPreStartupScreen(char16_t const*) Address = 0x1068c77f6 (filename not found) [in UnrealEditor]
GuardedMain(char16_t const*) Address = 0x1068be604 (filename not found) [in UnrealEditor]
-[UEAppDelegate runGameThread:] Address = 0x1068da033 (filename not found) [in UnrealEditor]
-[FCocoaGameThread main] Address = 0x10926b561 (filename not found) [in UnrealEditor-Core.dylib]
Unknown() Address = 0x7ff801a7f964 (filename not found) [in Foundation]
_pthread_start Address = 0x7ff800b644e1 (filename not found) [in libsystem_pthread.dylib]

**Comment by RobowilOFFICIAL** [comment]
Doesn't happen on my end.
